# Generated by Django 2.2.1 on 2019-10-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permisao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permisao',
        ),
    ]
